### ISSUE TITLE
Request for Guidance on Environment Deployment

### ISSUE THREAD

**Issue by Anonymous034** [smanolloff/vcmi-gym#1]
This is a great project, and I like HoMM3 too. Can I learn from you how to deploy this environment? Or would you be willing to guide me in deploying this environment?

**Comment by smanolloff** [comment]
Hi @Anonymous034, thank you for your interest in the project and I will surely try to come up with a how-to guide for building the project in the upcoming weeks. You can keep an eye on #2 (a similar request), so let's keep track of the progress there. I will close this one to avoid confusion.
Cheers!

**Comment by smanolloff** [comment]
@Anonymous034 please check https://github.com/smanolloff/vcmi-gym/issues/2 and reply there. Cheers

**Comment by Anonymous034** [comment]
Thanks!
