### ISSUE TITLE
Could you provide a comprehensive README document?

### ISSUE THREAD

**Issue by Warrior0x1** [smanolloff/vcmi-gym#2]
I am very interested in this project, but I haven't been able to successfully deploy the code. Could you provide me with some guidance? Thank you very much.

**Comment by smanolloff** [comment]
Hi @Warrior0x1, thank you for your interest in the project. I am actively working on the project and will try to come up with a how-to guide for building it in the upcoming weeks. Cheers!

**Comment by smanolloff** [comment]
@Warrior0x1 I have added some documentation, I hope you will find it helpful. Can you please see if it works for you?
